ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HAHM_asym_no_top_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_9 = ', GC_9
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_21 = ', GC_21
