ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=0D0)

      DOUBLE PRECISION MDL_MB,MDL_MC,MDL_MD,MDL_MMU,MDL_MS,MDL_MT
     $ ,MDL_MTA,MDL_MU,MDL_ME,MDL_MH,MDL_MS1,MDL_MS2

      COMMON/MASSES/ MDL_MB,MDL_MC,MDL_MD,MDL_MMU,MDL_MS,MDL_MT
     $ ,MDL_MTA,MDL_MU,MDL_ME,MDL_MH,MDL_MS1,MDL_MS2


      DOUBLE PRECISION MDL_WH,MDL_WT,MDL_WS1,MDL_WS2

      COMMON/WIDTHS/ MDL_WH,MDL_WT,MDL_WS1,MDL_WS2


      DOUBLE COMPLEX GC_4, GC_7, GC_8, GC_9, GC_10, GC_11, GC_13,
     $  GC_14, GC_15, GC_16, GC_17, GC_18, GC_20, GC_21

      COMMON/COUPLINGS/ GC_4, GC_7, GC_8, GC_9, GC_10, GC_11, GC_13,
     $  GC_14, GC_15, GC_16, GC_17, GC_18, GC_20, GC_21

