ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION MDL_SQRT__AS,MDL_G__EXP__2,MDL_NB__2__EXP__0_25
     $ ,MDL_SQRT__GF,MDL_V,MDL_MS1__EXP__2,MDL_V__EXP__2
     $ ,MDL_MB__EXP__2,MDL_MC__EXP__2,MDL_MD__EXP__2,MDL_MS__EXP__2
     $ ,MDL_MTA__EXP__2,MDL_MU__EXP__2,MDL_Y1,MDL_MS2__EXP__2,MDL_Y2
     $ ,MDL_SQRT__2,MDL_AEW,MDL_SQRT__AEW,MDL_EE,MDL_K,MDL_CT1,MDL_CT2
     $ ,MDL_CL,MDL_LAMBDA,MDL_HBAR,MDL_C,MDL_GF,AS,AEWM1

      COMMON/PARAMS_R/ MDL_SQRT__AS,MDL_G__EXP__2,MDL_NB__2__EXP__0_25
     $ ,MDL_SQRT__GF,MDL_V,MDL_MS1__EXP__2,MDL_V__EXP__2
     $ ,MDL_MB__EXP__2,MDL_MC__EXP__2,MDL_MD__EXP__2,MDL_MS__EXP__2
     $ ,MDL_MTA__EXP__2,MDL_MU__EXP__2,MDL_Y1,MDL_MS2__EXP__2,MDL_Y2
     $ ,MDL_SQRT__2,MDL_AEW,MDL_SQRT__AEW,MDL_EE,MDL_K,MDL_CT1,MDL_CT2
     $ ,MDL_CL,MDL_LAMBDA,MDL_HBAR,MDL_C,MDL_GF,AS,AEWM1


      DOUBLE COMPLEX MDL_COMPLEXI

      COMMON/PARAMS_C/ MDL_COMPLEXI


