ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_k = ', MDL_K
      WRITE(*,*) 'mdl_ct1 = ', MDL_CT1
      WRITE(*,*) 'mdl_ct2 = ', MDL_CT2
      WRITE(*,*) 'mdl_cl = ', MDL_CL
      WRITE(*,*) 'mdl_Lambda = ', MDL_LAMBDA
      WRITE(*,*) 'mdl_hbar = ', MDL_HBAR
      WRITE(*,*) 'mdl_c = ', MDL_C
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Me = ', MDL_ME
      WRITE(*,*) 'mdl_MMU = ', MDL_MMU
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MU = ', MDL_MU
      WRITE(*,*) 'mdl_MC = ', MDL_MC
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MD = ', MDL_MD
      WRITE(*,*) 'mdl_MS = ', MDL_MS
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_mh = ', MDL_MH
      WRITE(*,*) 'mdl_ms1 = ', MDL_MS1
      WRITE(*,*) 'mdl_ms2 = ', MDL_MS2
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_Ws1 = ', MDL_WS1
      WRITE(*,*) 'mdl_Ws2 = ', MDL_WS2
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_nb__2__exp__0_25 = ', MDL_NB__2__EXP__0_25
      WRITE(*,*) 'mdl_sqrt__Gf = ', MDL_SQRT__GF
      WRITE(*,*) 'mdl_v = ', MDL_V
      WRITE(*,*) 'mdl_ms1__exp__2 = ', MDL_MS1__EXP__2
      WRITE(*,*) 'mdl_v__exp__2 = ', MDL_V__EXP__2
      WRITE(*,*) 'mdl_MB__exp__2 = ', MDL_MB__EXP__2
      WRITE(*,*) 'mdl_MC__exp__2 = ', MDL_MC__EXP__2
      WRITE(*,*) 'mdl_MD__exp__2 = ', MDL_MD__EXP__2
      WRITE(*,*) 'mdl_MS__exp__2 = ', MDL_MS__EXP__2
      WRITE(*,*) 'mdl_MTA__exp__2 = ', MDL_MTA__EXP__2
      WRITE(*,*) 'mdl_MU__exp__2 = ', MDL_MU__EXP__2
      WRITE(*,*) 'mdl_y1 = ', MDL_Y1
      WRITE(*,*) 'mdl_ms2__exp__2 = ', MDL_MS2__EXP__2
      WRITE(*,*) 'mdl_y2 = ', MDL_Y2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
