ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=0D0)

      DOUBLE PRECISION MDL_MB,MDL_MC,MDL_MD,MDL_ME,MDL_MHSINPUT
     $ ,MDL_MHINPUT,MDL_MM,MDL_MS,MDL_MT,MDL_MTA,MDL_MU

      COMMON/MASSES/ MDL_MB,MDL_MC,MDL_MD,MDL_ME,MDL_MHSINPUT
     $ ,MDL_MHINPUT,MDL_MM,MDL_MS,MDL_MT,MDL_MTA,MDL_MU


      DOUBLE PRECISION MDL_WH,MDL_WHS,MDL_WT

      COMMON/WIDTHS/ MDL_WH,MDL_WHS,MDL_WT


      DOUBLE COMPLEX GC_3, GC_17, GC_20, GC_22, GC_24, GC_26, GC_28,
     $  GC_30, GC_32, GC_34, GC_36

      COMMON/COUPLINGS/ GC_3, GC_17, GC_20, GC_22, GC_24, GC_26, GC_28
     $ , GC_30, GC_32, GC_34, GC_36

