ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HAHM_gluons_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_28 = ', GC_28
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_36 = ', GC_36
