ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_kap = ', MDL_KAP
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymd = ', MDL_YMD
      WRITE(*,*) 'mdl_ymu = ', MDL_YMU
      WRITE(*,*) 'mdl_yms = ', MDL_YMS
      WRITE(*,*) 'mdl_ymc = ', MDL_YMC
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymel = ', MDL_YMEL
      WRITE(*,*) 'mdl_ymmu = ', MDL_YMMU
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_xi = ', MDL_XI
      WRITE(*,*) 'mdl_ME = ', MDL_ME
      WRITE(*,*) 'mdl_MM = ', MDL_MM
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MU = ', MDL_MU
      WRITE(*,*) 'mdl_MC = ', MDL_MC
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MD = ', MDL_MD
      WRITE(*,*) 'mdl_MS = ', MDL_MS
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MHinput = ', MDL_MHINPUT
      WRITE(*,*) 'mdl_MHSinput = ', MDL_MHSINPUT
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WHS = ', MDL_WHS
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_nb__2__exp__0_25 = ', MDL_NB__2__EXP__0_25
      WRITE(*,*) 'mdl_sqrt__Gf = ', MDL_SQRT__GF
      WRITE(*,*) 'mdl_v = ', MDL_V
      WRITE(*,*) 'mdl_MHinput__exp__2 = ', MDL_MHINPUT__EXP__2
      WRITE(*,*) 'mdl_MHSinput__exp__2 = ', MDL_MHSINPUT__EXP__2
      WRITE(*,*) 'mdl_kap__exp__2 = ', MDL_KAP__EXP__2
      WRITE(*,*) 'mdl_v__exp__2 = ', MDL_V__EXP__2
      WRITE(*,*) 'mdl_xi__exp__2 = ', MDL_XI__EXP__2
      WRITE(*,*) 'mdl_th = ', MDL_TH
      WRITE(*,*) 'mdl_MHinput__exp__6 = ', MDL_MHINPUT__EXP__6
      WRITE(*,*) 'mdl_MT__exp__6 = ', MDL_MT__EXP__6
      WRITE(*,*) 'mdl_MHinput__exp__4 = ', MDL_MHINPUT__EXP__4
      WRITE(*,*) 'mdl_MT__exp__4 = ', MDL_MT__EXP__4
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_rho = ', MDL_RHO
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yc = ', MDL_YC
      WRITE(*,*) 'mdl_yd = ', MDL_YD
      WRITE(*,*) 'mdl_ye = ', MDL_YE
      WRITE(*,*) 'mdl_ym = ', MDL_YM
      WRITE(*,*) 'mdl_ys = ', MDL_YS
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_yu = ', MDL_YU
      WRITE(*,*) 'mdl_th__exp__2 = ', MDL_TH__EXP__2
      WRITE(*,*) 'mdl_ch = ', MDL_CH
      WRITE(*,*) 'mdl_muH2 = ', MDL_MUH2
      WRITE(*,*) 'mdl_muSM2 = ', MDL_MUSM2
      WRITE(*,*) 'mdl_sh = ', MDL_SH
      WRITE(*,*) 'mdl_MHinput__exp__12 = ', MDL_MHINPUT__EXP__12
      WRITE(*,*) 'mdl_MW__exp__12 = ', MDL_MW__EXP__12
      WRITE(*,*) 'mdl_MHinput__exp__10 = ', MDL_MHINPUT__EXP__10
      WRITE(*,*) 'mdl_MW__exp__10 = ', MDL_MW__EXP__10
      WRITE(*,*) 'mdl_MHinput__exp__8 = ', MDL_MHINPUT__EXP__8
      WRITE(*,*) 'mdl_MW__exp__8 = ', MDL_MW__EXP__8
      WRITE(*,*) 'mdl_MW__exp__6 = ', MDL_MW__EXP__6
      WRITE(*,*) 'mdl_MW__exp__4 = ', MDL_MW__EXP__4
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_ch__exp__3 = ', MDL_CH__EXP__3
      WRITE(*,*) 'mdl_sh__exp__3 = ', MDL_SH__EXP__3
      WRITE(*,*) 'mdl_ch__exp__4 = ', MDL_CH__EXP__4
      WRITE(*,*) 'mdl_ch__exp__2 = ', MDL_CH__EXP__2
      WRITE(*,*) 'mdl_sh__exp__2 = ', MDL_SH__EXP__2
      WRITE(*,*) 'mdl_sh__exp__4 = ', MDL_SH__EXP__4
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_AH = ', MDL_AH
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_GH = ', MDL_GH
